name: Terraform Destroy Environment

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Select YES to confirm destruction of all Terraform-managed resources"
        required: true
        type: choice
        options:
          - "NO"
          - "YES"
        default: "NO"

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_destroy == 'YES' }}
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: .github/terraform
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.TF_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ vars.TF_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ vars.TF_CONTAINER_NAME }}" \
          -backend-config="key=${{ vars.TF_STATE_KEY }}"

      - name: Terraform Destroy
        working-directory: .github/terraform
        run: terraform destroy -auto-approve