name: Terraform Azure Deploy

on:
#   push:
#     branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

    #   - name: Azure Login
    #     uses: azure/login@v2
    #     with:
    #       creds: {{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: .github/terraform
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.TF_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ vars.TF_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ vars.TF_CONTAINER_NAME }}" \
          -backend-config="key=${{ vars.TF_STATE_KEY }}"

      - name: Terraform Plan
        working-directory: .github/terraform
        env:
            TF_VAR_location: "westeurope"
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: .github/terraform
        run: terraform apply -auto-approve tfplan