name: Terraform Azure Deploy

on:
#   push:
#     branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.TF_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ vars.TF_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ vars.TF_CONTAINER_NAME }}" \
          -backend-config="key=${{ vars.TF_STATE_KEY }}"

      - name: Terraform Plan
        env:
            TF_VAR_location: "westeurope"
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan