name: Terraform Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true

jobs:
  terraform:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
            TF_VAR_env: "${{ inputs.environment }}"
            TF_VAR_location: "westeurope"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: ./terraform/${{ inputs.environment }}/
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.TF_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ vars.TF_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=${{ vars.TF_CONTAINER_NAME }}" \
          -backend-config="key=${{ inputs.environment }}.tfstate"

      - name: Terraform Plan
        working-directory: ./terraform/${{ inputs.environment }}/
        run: terraform plan -var="env=${{ inputs.environment }}"

      - name: Terraform Apply
        working-directory: ./terraform/${{ inputs.environment }}/
        run: terraform apply -auto-approve -var="env=${{ inputs.environment }}"
